### PR TITLE
Add support for mermaidjs diagrams

### PR DESCRIPTION
**Pull request by mreid-moz**
Incorporate the "mermaid-gb3" gitbook plugin, and migrate the
pipeline overview chart as an example.

Addresses #78.

### CODE REVIEW

**Comment by mreid-moz** [comment]
For comparison purposes, here's a screenshot of the original diagram:
screen shot 2018-01-19 at 11 23 57 am


And here's the mermaid-generated one:
screen shot 2018-01-19 at 11 25 09 am

**Comment by fbertsch** [comment]
@mreid-moz the new diagram definitely seems more difficult to follow than the older one. I think the colors and images really make it straightforward to understand, any way we could keep those using Mermaid?

**Comment by mreid-moz** [comment]
You can [style the nodes an edges](https://mermaidjs.github.io/flowchart.html#styling-and-classes), but I'm not sure you can easily keep the images.

**Comment by chutten** [comment]
`background-image: url(...);` is a style...

**Comment by mreid-moz** [comment]
@chutten I couldn't get `background-image` to work for styling, if you can make it work [in the playground/editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKICBGaXJlZm94KChmYTpmYS1maXJlZm94IEZpcmVmb3gpKS0tPnxKU09OfCBFTEIKICBzdHlsZSBGaXJlZm94IGZpbGw6I2Y2MSxzdHJva2Utd2lkdGg6MnB4CiAgRUxCW0xvYWQgQmFsYW5jZXJdLS0-fEpTT058IG5naW54CiAgbmdpbngtLT58SlNPTnwgTGFuZGZpbGwoZmE6ZmEtZGF0YWJhc2UgUzMgTGFuZGZpbGwpCiAgbmdpbngtLT58cHJvdG9idWZ8IEthZmthW2ZhOmZhLWZpbGVzLW8gS2Fma2FdCiAgS2Fma2EtLT58cHJvdG9idWZ8IENFUChIaW5kc2lnaHQgQ0VQKQogIEthZmthLS0-fHByb3RvYnVmfCBEV0woSGluZHNpZ2h0IERXTCkKICBDRVAtLT4gSFNVSShIaW5kc2lnaHQgVUkpCiAgRFdMLS0-fHByb3RvYnVmfCBkYXRhbGFrZShmYTpmYS1kYXRhYmFzZSBTMyBEYXRhIExha2UpCiAgRFdMLS0-fHBhcnF1ZXR8IGRhdGFsYWtlCiAgZGF0YWxha2UtLT58cGFycXVldHwgcHJlc3RvZGIKICBwcmVzdG9kYi0tPnJlZGFzaFtmYTpmYS1saW5lLWNoYXJ0IFJlOmRhc2hdCiAgZGF0YWxha2UtLT5TcGFyawogIFNwYXJrLS0-ZGF0YWxha2UKICBBaXJmbG93W2ZhOmZhLWNsb2NrLW8gQWlyZmxvd10tLT58U2NoZWR1bGVkIHRhc2tzfFNwYXJre2ZhOmZhLXN0YXIgU3Bhcmt9CiAgU3BhcmstLT58YWdncmVnYXRpb25zfFJEQk1TKGZhOmZhLWRhdGFiYXNlIFBvc3RncmVTUUwpCiAgUkRCTVMtLT5UTU9bZmE6ZmEtYmFyLWNoYXJ0IFRNT10KICBSREJNUy0tPkNlcmJlcnVzW2ZhOmZhLXNlYXJjaC1wbHVzIENlcmJlcnVzXQ) we can use it.

**Comment by chutten** [comment]
Oh, bother, it's SVG, isn't it. Never mind me. I don't know if it's possible to embed a raster image into a svg fill.

**Comment by harterrt** [comment]
Woot. 

I agree, this diagram is harder to follow. However, I think this is a big enough maintainability win to merge. Let's try to get the background images working while this is fresh in our minds, but not block on it.

Technical note: It looks like this rendering does happen client side. Not a problem though.

**Comment by fbertsch** [comment]
Before we merge, can we at least give different colors to components? That would be a readability win.

**Comment by chutten** [comment]
Or... y'know, we could leave the previous graph in place as a jpeg and simply add mermaid as the dependency?

**Comment by mreid-moz** [comment]
> Before we merge, can we at least give different colors to components? That would be a readability win.

Yep, that should be relatively easy.

> Or... y'know, we could leave the previous graph in place as a jpeg and simply add mermaid as the dependency?

The previous diagram needed a change (removing HBase) which was not apparent, but *would* be after this change!

**Comment by mreid-moz** [comment]
@fbertsch r? on [this colour scheme](https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKICBmaXJlZm94KChmYTpmYS1maXJlZm94IEZpcmVmb3gpKS0tPnxKU09OfCBlbGIKICBlbGJbTG9hZCBCYWxhbmNlcl0tLT58SlNPTnwgbmdpbngKICBuZ2lueC0tPnxKU09OfCBsYW5kZmlsbChmYTpmYS1kYXRhYmFzZSBTMyBMYW5kZmlsbCkKICBuZ2lueC0tPnxwcm90b2J1Znwga2Fma2FbZmE6ZmEtZmlsZXMtbyBLYWZrYV0KICBrYWZrYS0tPnxwcm90b2J1ZnwgY2VwKEhpbmRzaWdodCBDRVApCiAga2Fma2EtLT58cHJvdG9idWZ8IGR3bChIaW5kc2lnaHQgRFdMKQogIGNlcC0tPiBoc3VpKEhpbmRzaWdodCBVSSkKICBkd2wtLT58cHJvdG9idWZ8IGRhdGFsYWtlKGZhOmZhLWRhdGFiYXNlIFMzIERhdGEgTGFrZSkKICBkd2wtLT58cGFycXVldHwgZGF0YWxha2UKICBkYXRhbGFrZS0tPnxwYXJxdWV0fCBwcmVzdG9kYgogIHByZXN0b2RiLS0-cmVkYXNoW2ZhOmZhLWxpbmUtY2hhcnQgUmU6ZGFzaF0KICBkYXRhbGFrZS0tPnNwYXJrCiAgc3BhcmstLT5kYXRhbGFrZQogIGFpcmZsb3dbZmE6ZmEtY2xvY2stbyBBaXJmbG93XS0tPnxTY2hlZHVsZWQgdGFza3N8c3Bhcmt7ZmE6ZmEtc3RhciBTcGFya30KICBzcGFyay0tPnxhZ2dyZWdhdGlvbnN8cmRibXMoZmE6ZmEtZGF0YWJhc2UgUG9zdGdyZVNRTCkKICByZGJtcy0tPnRtb1tmYTpmYS1iYXItY2hhcnQgVE1PXQogIHJkYm1zLS0-Y2VyYmVydXNbZmE6ZmEtc2VhcmNoLXBsdXMgQ2VyYmVydXNdCgoKc3R5bGUgZmlyZWZveCBmaWxsOiNmNjEKc3R5bGUgZWxiIGZpbGw6Izc3NwpzdHlsZSBuZ2lueCBmaWxsOmdyZWVuCnN0eWxlIGxhbmRmaWxsIGZpbGw6dG9tYXRvCnN0eWxlIGRhdGFsYWtlIGZpbGw6dG9tYXRvCnN0eWxlIGthZmthIGZpbGw6I2FhYQpzdHlsZSBjZXAgZmlsbDpwYWxlZ29sZGVucm9kCnN0eWxlIGR3bCBmaWxsOnBhbGVnb2xkZW5yb2QKc3R5bGUgaHN1aSBmaWxsOnBhbGVnb2xkZW5yb2QKc3R5bGUgcHJlc3RvZGIgZmlsbDpjb3JuZmxvd2VyYmx1ZQpzdHlsZSByZWRhc2ggZmlsbDpzYWxtb24Kc3R5bGUgc3BhcmsgZmlsbDpkYXJrb3JhbmdlCnN0eWxlIGFpcmZsb3cgZmlsbDpsYXduZ3JlZW4Kc3R5bGUgcmRibXMgZmlsbDpjb3JuZmxvd2VyYmx1ZQpzdHlsZSB0bW8gZmlsbDpsaWdodGdyZXkKc3R5bGUgY2VyYmVydXMgZmlsbDpyb3lhbGJsdWU)

**Comment by fbertsch** [comment]
r+, much more readable @mreid-moz!

**Comment by fbertsch** [comment]
@mreid-moz hold up, we seem to have lost some of the icons.

**Comment by mreid-moz** [comment]
the icons don't show in that online editor. they work in the docs though.

**Pull request merged**
