### PR TITLE
Include a brief history of the churn dataset

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This adds a brief history of the churn dataset with links to the original bugs.

### CODE REVIEW

**Comment by harterrt** [comment]
@acmiyaguchi - is this ready to merge?

**Comment by harterrt** [comment]
Friendly ping, @acmiyaguchi

**Comment by acmiyaguchi** [comment]
This fell off my radar, I still have to do the link checking for the Mana page.

**Comment by acmiyaguchi** [comment]
Link-checking looks fine, closing this out.

**Pull request merged**
