### PR TITLE
Replace gitbook with mdbook

### LINKED ISSUE #162: Alternatives to GitBook for publishing documentation
As I was talking with @Dexterp37, I noticed that you are using GitBook to generate https://docs.telemetry.mozilla.org/

I wonder if you already evaluated alternatives, given that the CLI is not developed anymore, and GitBook is focusing on hosted documentation.
https://github.com/GitbookIO/gitbook/issues/1808

### PR DESCRIPTION
**Pull request by badboy**
This replaces gitbook with [mdbook](https://github.com/rust-lang-nursery/mdBook).

It currently uses the [mdbook-dtmo](https://github.com/badboy/mdbook-dtmo) wrapper, which bundles plugins for mermaid and ToC. Binary releases for Linux, Mac and Windows are provided [on the release page](https://github.com/badboy/mdbook-dtmo/releases) (though Windows untested).
It's based on the latest git version of mdbook, which includes relevant bug fixes. I intend to update it to a stable released version of mdbook as soon as it gets a release.

Upstreaming/changing how we do the mermaid/toc processing is tracked in #186.

Known remaining issues:

- I had to add empty chapters for some parts, see commit https://github.com/mozilla/firefox-data-docs/commit/ffdc0b09fc81aa9cec0d398a37d6d20380680016
- I had to remove the top-level "Bug template" link and moved it to the "Contributing" chapter

Live view: https://badboy.github.io/firefox-data-docs/
Fixes #162, #149 

I can hold this back until the currently open PRs are merged and rebase it on top of that or I can help with rebasing the PRs after the fact.

### CODE REVIEW

**Comment by badboy** [comment]
Yeah, live view is linked: https://badboy.github.io/firefox-data-docs/
I wonder about the rustc thing, because in _theory_ that should not be necessary, but I'll double-check. I will add the additional deps though.

What's the right place to announce this?

**Comment by harterrt** [comment]
Huh, I don't know where to announce this. @mreid-moz any ideas? I want to at least hit the folks reporting up through matt_g, rweiss, and kparlante.

Let's give the recipients a grace period by which to get straggling PRs submitted. Say 1week? Does that sound like a problem @badboy ?

**Comment by badboy** [comment]
Nope, timing is less critical for me. I have a script to do most of the changes automatically, so I can easily work of whatever is merged by then.

**Comment by mreid-moz** [comment]
`fx-data-platform` sounds good to me. `fx-data-dev` would be good too, it is a bit broader (and public) and may find more people who are interested.

**Comment by badboy** [comment]
Will take care of fixing the above mentioned things and then also send a mail out.

**Comment by badboy** [comment]
I updated the code with the comments above.
IMO it would be fine to merge this by October 8th, giving a full week for gathering feedback. Anything that's merged until then will be migrated as well.

@harterrt With your ok I would send out a mail to fx-data-dev and fx-data-platform with this content: https://gist.github.com/badboy/2733a5c1a6c253c681200a5711631edd

**Comment by harterrt** [comment]
Sounds like a plan, @badboy. That email looks great, go for it!

**Comment by badboy** [comment]
@chutten The generated SVG by mermaid.js is empty. I'm looking into this.

**Comment by badboy** [comment]
Found the problem. Fixing and redeploying.

**Comment by badboy** [comment]
Thanks, @mreid-moz. I fixed those links and also ran a link checker locally to ensure there are no broken links hiding. I rebased on top of the latest master changes and ensure the new docu is rendering fine as well.

**Comment by badboy** [comment]
I had to use absolute URLs for included files. These are already broken in the current version. I added them to the ignore list of the link checker.

**Comment by mreid-moz** [comment]
> I had to use absolute URLs for included files. These are already broken in the current version. I added them to the ignore list of the link checker.

Does this mean we won't have link-checking for internal links?

**Comment by mreid-moz** [comment]
> "Running a link checker" sounds like either a good checker for the repo or a decent thing to document in README or CONTRIBUTING or someplace.

It's documented [here](https://github.com/mozilla/firefox-data-docs/blob/34fd1ae79498d870d6fa13d89dc874b647a47206/src/meta/contributing.md#link-checking) (or [here](https://docs.telemetry.mozilla.org/meta/contributing.html#link-checking) in the "live" docs).

**Comment by badboy** [comment]
We do have the markdown-link-checker, which does work and mdbook translates links to markdown files into the appropriate links to the rendered html file.

However, we have some files that are included in different parts, that used relative links to markdown files. Those files in markdown are correct from the point of view of that single markdown file, but incorrect when rendered, as they are included elsewhere.
These links are already currently broken, e.g. the `telemetry_new_profile_parquet` link on https://docs.telemetry.mozilla.org/concepts/choosing_a_dataset.html#firstshutdownsummary

I can see if I can somehow add a link-checker on the actual rendered content to CI, though I hope this would not block this PR.

**Comment by badboy** [comment]
Just pushed the latest rebase to include changes to the project listing.

@harterrt From my side it would be ready to go. I would handle the link-checker thing in a follow-up, if that's ok.

**Comment by badboy** [comment]
[There is now](https://github.com/mozilla/firefox-data-docs/issues/195)

**Pull request merged**
